gateway:
  security:
    enabled: false
  routes:
    alert: ${ALERT_SERVICE_URI:http://localhost:9001}
    scheduler: ${SCHEDULER_SERVICE_URI:http://localhost:9002}
    audit: ${AUDIT_SERVICE_URI:http://localhost:9003}

spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
